

development: &db
  adapter: mysql2
  encoding: utf8
  database: db_45001893n1
  username: user45001893n1
  password: enaidpGs
  host:     ny.railshoster.de

test:
  <<: *db

  database: db_45001893n3
  username: user45001893n3
  password: CFx3jHDS
  host:     ny.railshoster.de

production:
  <<: *db

  database: db_45001893n2
  username: user45001893n2
  password: A67H1pLG
  host:     ny.railshoster.de









