# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
#   Tables:
table1 = PromTable.create(position: 0, orientation: 'promenade', caption:  '', seat_description: 'Flanierkarte', price: nil)
table2 = PromTable.create(position: 1, orientation: 'horizontal', caption:  'Tisch 1', seat_description: 'Platzkarte', price: 295)
table3 = PromTable.create(position: 2, orientation: 'horizontal', caption:  'Tisch 2', seat_description: 'Platzkarte', price: 295)
table4 = PromTable.create(position: 3, orientation: 'horizontal', caption: 'Tisch 3', seat_description: 'Platzkarte', price: 295)
table5 = PromTable.create(position: 4, orientation: 'horizontal', caption: 'Tisch 4', seat_description: 'Platzkarte', price: 295)
table6 = PromTable.create(position: 5, orientation: 'horizontal', caption: 'Tisch 5', seat_description: 'Platzkarte', price: 295)
table7 = PromTable.create(position: 6, orientation: 'vertical', caption: 'Tisch 6', seat_description: 'Platzkarte', price: 295)
table8 = PromTable.create(position: 7, orientation: 'vertical', caption: 'Tisch 7', seat_description: 'Platzkarte', price: 295)
table9 = PromTable.create(position: 8, orientation: 'vertical', caption: 'Tisch 8', seat_description: 'Platzkarte', price: 295)
table10 = PromTable.create(position: 9, orientation: 'vertical', caption: 'Tisch 9', seat_description: 'Platzkarte', price: 295)
table11 = PromTable.create(position: 10, orientation: 'vertical', caption: 'Tisch 10', seat_description: 'Platzkarte', price: 295)
table12 = PromTable.create(position: 11, orientation: 'vertical', caption: 'Tisch 11', seat_description: 'Platzkarte', price: 295)
table13 = PromTable.create(position: 12, orientation: 'vertical', caption: 'Tisch 12', seat_description: 'Platzkarte', price: 295)
table14 = PromTable.create(position: 13, orientation: 'vertical', caption: 'Tisch 13', seat_description: 'Platzkarte', price: 295)
table15 = PromTable.create(position: 14, orientation: 'vertical', caption: 'Tisch 14', seat_description: 'Platzkarte', price: 295)
table16 = PromTable.create(position: 15, orientation: 'vertical', caption:  'Tisch 15', seat_description: 'Platzkarte', price: 295)
table17 = PromTable.create(position: 16, orientation: 'horizontal', caption: 'Tisch 16 (Lehrer)', seat_description: 'Platzkarte', price: 295)
table18 = PromTable.create(position: 17, orientation: 'horizontal', caption: 'Tisch 17 (Lehrer)', seat_description: 'Platzkarte', price: 295)
table19 = PromTable.create(position: 18, orientation: 'horizontal', caption: 'Tisch 18 (Lehrer)', seat_description: 'Platzkarte', price: 295)
table20 = PromTable.create(position: 19, orientation: 'horizontal', caption: 'Tisch 19', seat_description: 'Platzkarte', price: 295)

#   Seats:
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table1, position: 1, caption: '', price: 9.99, status: 0)
Seat.create(prom_table: table2, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table2, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table3, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table4, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table5, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table6, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table7, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table8, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table9, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table10, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table11, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table12, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table13, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table14, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table15, position: 10, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table16, position: 10, caption: '', price: 33, status: 0)

Seat.create(prom_table: table17, position: 1, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 2, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 3, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 4, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 5, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 6, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 7, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 8, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 9, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table17, position: 10, caption: '', price: 29.5, status: 0)

Seat.create(prom_table: table18, position: 1, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 2, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 3, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 4, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 5, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 6, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 7, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 8, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 9, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table18, position: 10, caption: '', price: 29.5, status: 0)

Seat.create(prom_table: table19, position: 1, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 2, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 3, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 4, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 5, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 6, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 7, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 8, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 9, caption: '', price: 29.5, status: 0)
Seat.create(prom_table: table19, position: 10, caption: '', price: 29.5, status: 0)

Seat.create(prom_table: table20, position: 1, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 2, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 3, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 4, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 5, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 6, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 7, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 8, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 9, caption: '', price: 33, status: 0)
Seat.create(prom_table: table20, position: 10, caption: '', price: 33, status: 0)
